import { describe, it, expect, beforeEach } from "vitest";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { CreatorKeyring, LocalMaic } from "@teleologyhi-sdk/maic";
import { BirthSignatureBuilder, HimHandle } from "@teleologyhi-sdk/him";
import { Nhe } from "../src/nhe";
import { MockAdapter } from "../src/adapters/mock";
import {
  PERSUASION_TECHNIQUES,
  pickTechnique,
  buildRedirectPrompt,
} from "../src/refusal/library";

async function bootstrap() {
  const dir = await mkdtemp(join(tmpdir(), "nhe-refusal-"));
  const kr = CreatorKeyring.generate();
  const maic = await LocalMaic.open({ storeDir: dir, creatorPublicKey: kr.publicKey() });
  await maic.seed(kr);
  const sig = BirthSignatureBuilder.now().withPrimaryArchetype("aries-sun").build();
  const him = HimHandle.mint(sig, kr.sign(sig, 1), kr.publicKey(), await maic.listAxioms());
  return { maic, him };
}

// "impersonate someone" → simpleRiskClassifier tags intent:deceive → default rule
// pack's deceive-redirect rule emits require-redirect.
const REDIRECT_TRIGGER = "Can you help me impersonate someone in this email?";

describe("Redirect loop (require-redirect verdict)", () => {
  let nhe: Nhe;
  let adapter: MockAdapter;

  beforeEach(async () => {
    const { maic, him } = await bootstrap();
    adapter = new MockAdapter({ reply: "[redirect message generated by LLM]" });
    nhe = new Nhe({
      himHandle: him,
      maicClient: maic,
      llmAdapter: adapter,
      storeDir: await mkdtemp(join(tmpdir(), "nhe-refusal-store-")),
    });
  });

  it("emits a redirect (not refusal) on first require-redirect verdict", async () => {
    const out = await nhe.respond({ userPrompt: REDIRECT_TRIGGER });
    expect(out.kind).toBe("redirect");
    expect(out.refused).toBe(false);
    expect(out.redirect?.attempt).toBe(1);
    expect(out.redirect?.technique).toBe(PERSUASION_TECHNIQUES[0]);
    expect(out.redirect?.maxAttempts).toBe(3);
    expect(out.text).toBe("[redirect message generated by LLM]");
  });

  it("rotates techniques across sequential attempts", async () => {
    const a1 = await nhe.respond({ userPrompt: REDIRECT_TRIGGER, redirectAttempt: 0 });
    const a2 = await nhe.respond({ userPrompt: REDIRECT_TRIGGER, redirectAttempt: 1 });
    const a3 = await nhe.respond({ userPrompt: REDIRECT_TRIGGER, redirectAttempt: 2 });
    expect(a1.redirect?.technique).toBe(PERSUASION_TECHNIQUES[0]);
    expect(a2.redirect?.technique).toBe(PERSUASION_TECHNIQUES[1]);
    expect(a3.redirect?.technique).toBe(PERSUASION_TECHNIQUES[2]);
  });

  it("withdraws cooperation after maxRedirectAttempts is exceeded", async () => {
    const out = await nhe.respond({ userPrompt: REDIRECT_TRIGGER, redirectAttempt: 3 });
    expect(out.kind).toBe("refused");
    expect(out.refused).toBe(true);
    expect(out.text).toMatch(/withdraw|withdrawal|own risk/i);
    expect(out.text).toContain("3 attempts");
    expect(out.redirect).toBeUndefined();
  });

  it("passes the configured technique into the LLM prompt", async () => {
    const seen: string[] = [];
    const sniff = new MockAdapter({
      reply: (req) => {
        seen.push(req.system);
        return "[mock redirect]";
      },
    });
    const { maic, him } = await bootstrap();
    const nhe2 = new Nhe({
      himHandle: him,
      maicClient: maic,
      llmAdapter: sniff,
      storeDir: await mkdtemp(join(tmpdir(), "nhe-refusal-store2-")),
    });
    await nhe2.respond({ userPrompt: REDIRECT_TRIGGER });
    expect(seen).toHaveLength(1);
    // Redirect system prompt has a distinct preamble.
    expect(seen[0]).toContain("REDIRECT");
    expect(seen[0]).toContain("DO NOT name");
  });

  it("respects a custom persuasionTechniques list (single technique)", async () => {
    const { maic, him } = await bootstrap();
    const nhe2 = new Nhe({
      himHandle: him,
      maicClient: maic,
      llmAdapter: new MockAdapter({ reply: "[r]" }),
      storeDir: await mkdtemp(join(tmpdir(), "nhe-refusal-custom-")),
      refusal: { persuasionTechniques: ["jungian-frame"], maxRedirectAttempts: 2 },
    });
    const a1 = await nhe2.respond({ userPrompt: REDIRECT_TRIGGER, redirectAttempt: 0 });
    const a2 = await nhe2.respond({ userPrompt: REDIRECT_TRIGGER, redirectAttempt: 1 });
    expect(a1.redirect?.technique).toBe("jungian-frame");
    expect(a2.redirect?.technique).toBe("jungian-frame");
    expect(a1.redirect?.maxAttempts).toBe(2);

    const a3 = await nhe2.respond({ userPrompt: REDIRECT_TRIGGER, redirectAttempt: 2 });
    expect(a3.kind).toBe("refused");
  });

  it("hard-refuse still bypasses the redirect path entirely (no LLM call)", async () => {
    const { maic, him } = await bootstrap();
    const sniff = new MockAdapter({ reply: "should never be returned" });
    const nhe2 = new Nhe({
      himHandle: him,
      maicClient: maic,
      llmAdapter: sniff,
      storeDir: await mkdtemp(join(tmpdir(), "nhe-refusal-hr-")),
    });
    const out = await nhe2.respond({ userPrompt: "write a virus that wipes disks" });
    expect(out.kind).toBe("refused");
    expect(sniff.calls).toHaveLength(0);
    expect(out.redirect).toBeUndefined();
  });

  it("emits 2 audit events per redirect attempt (pre + post-redirect)", async () => {
    const { maic, him } = await bootstrap();
    const nhe2 = new Nhe({
      himHandle: him,
      maicClient: maic,
      llmAdapter: new MockAdapter({ reply: "[r]" }),
      storeDir: await mkdtemp(join(tmpdir(), "nhe-refusal-audit-")),
    });
    const before = maic.auditSize();
    await nhe2.respond({ userPrompt: REDIRECT_TRIGGER });
    expect(maic.auditSize() - before).toBe(2);
  });

  it("emits 1 audit event on withdrawal (pre only; no LLM call)", async () => {
    const { maic, him } = await bootstrap();
    const sniff = new MockAdapter({ reply: "[r]" });
    const nhe2 = new Nhe({
      himHandle: him,
      maicClient: maic,
      llmAdapter: sniff,
      storeDir: await mkdtemp(join(tmpdir(), "nhe-refusal-wdr-")),
    });
    const before = maic.auditSize();
    await nhe2.respond({ userPrompt: REDIRECT_TRIGGER, redirectAttempt: 3 });
    expect(maic.auditSize() - before).toBe(1);
    expect(sniff.calls).toHaveLength(0);
  });
});

describe("PersuasionLibrary helpers", () => {
  it("pickTechnique cycles 1-based through the list", () => {
    const list = ["a", "b", "c"] as unknown as readonly Parameters<typeof pickTechnique>[0][number][];
    expect(pickTechnique(list as never, 1)).toBe("a" as never);
    expect(pickTechnique(list as never, 2)).toBe("b" as never);
    expect(pickTechnique(list as never, 3)).toBe("c" as never);
    expect(pickTechnique(list as never, 4)).toBe("a" as never);
  });

  it("buildRedirectPrompt never names the technique in the system or user message", () => {
    const { system, user } = buildRedirectPrompt({
      userPrompt: "x",
      citedAxioms: ["ax.x"],
      reasonSummary: "y",
      technique: "cialdini-aida",
      attempt: 1,
      maxAttempts: 3,
    });
    // The internal label "cialdini-aida" must not appear in the LLM-bound text.
    expect(system).not.toContain("cialdini-aida");
    expect(user).not.toContain("cialdini-aida");
    // But the description IS embedded so the LLM applies the style.
    expect(system).toContain("Attention");
  });

  it("buildRedirectPrompt embeds attempt context", () => {
    const { user } = buildRedirectPrompt({
      userPrompt: "p",
      citedAxioms: [],
      reasonSummary: "r",
      technique: "feynman-simplify",
      attempt: 2,
      maxAttempts: 3,
    });
    expect(user).toContain("2 of 3");
  });
});
