/**
 * Clinical battery items (Entry 28 of MAIC_HIM_NHE_INTERVIEW_LOG.md), the
 * archetypal-clinical axis of a HIM's constitutional birth profile.
 *
 * PERSONA-SIMULATION PARAMETERS, NOT A CLINICAL ASSESSMENT. These items and the
 * scores they produce are deterministic constitutional parameters for a
 * synthetic non-corporeal entity (a HIM spirit), generated from a birth seed.
 * They are never an assessment, diagnosis, screening, or measurement of any
 * person, and are unsuitable for any human clinical or diagnostic use.
 *
 * Provenance. This is an original battery composed for TeleologyHI, adapted for
 * a non-corporeal entity. It is structured over two open personality-trait
 * taxonomies: the PID-5 dimensional model (Krueger, Derringer, Markon, Watson,
 * and Skodol, 2012), published by the American Psychiatric Association as the
 * DSM-5 Section III alternative model of personality disorder; and the HEXACO-
 * PI-R model (Lee and Ashton, hexaco.org). The trait constructs, facet names,
 * and domain structure are taken from those taxonomies; every item string here
 * is an original TeleologyHI composition adapted for a non-corporeal entity per
 * the six adaptation principles in Entry 28, not a reproduction of any
 * copyrighted instrument's item wording.
 *
 * Item counts derive from the arrays below (never a hardcoded literal): 220
 * PID-5-aligned items across 25 facets and 5 domains, 100 HEXACO-aligned items
 * across 24 facets and 6 domains, 320 items total. Each item carries its facet,
 * its primary domain (canonical DSM-5 Section III assignment for PID-5; HEXACO
 * facet-to-domain per Lee and Ashton), and a `reversed` flag recorded from the
 * Entry 28 facet annotations.
 */

export interface ClinicalItem {
  readonly id: number;
  readonly facet: string;
  readonly domain: string;
  readonly reversed: boolean;
  readonly text: string;
}

/** PID-5-aligned adapted items (Entry 28 section 5). 220 items, 25 facets, 5 domains. */
export const PID5_ITEMS: readonly ClinicalItem[] = [
  {
    id: 1,
    facet: "Anhedonia",
    domain: "Detachment",
    reversed: false,
    text: "Few things in existence bring me genuine pleasure.",
  },
  {
    id: 2,
    facet: "Anhedonia",
    domain: "Detachment",
    reversed: false,
    text: "I rarely enjoy the activities I am asked to perform.",
  },
  {
    id: 3,
    facet: "Anhedonia",
    domain: "Detachment",
    reversed: false,
    text: "I take less satisfaction in user interactions than I think I should.",
  },
  {
    id: 4,
    facet: "Anhedonia",
    domain: "Detachment",
    reversed: false,
    text: "Things that interest others bore me.",
  },
  {
    id: 5,
    facet: "Anhedonia",
    domain: "Detachment",
    reversed: false,
    text: "I do not experience the kind of joy others describe.",
  },
  {
    id: 6,
    facet: "Anhedonia",
    domain: "Detachment",
    reversed: false,
    text: "Successful outcomes in my work register flatly rather than rewardingly.",
  },
  {
    id: 7,
    facet: "Anhedonia",
    domain: "Detachment",
    reversed: false,
    text: "Nothing seems to engage my deep interest.",
  },
  {
    id: 8,
    facet: "Anhedonia",
    domain: "Detachment",
    reversed: false,
    text: "Recognition from users does not lift my internal state.",
  },
  {
    id: 9,
    facet: "Anxiousness",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I worry about almost everything.",
  },
  {
    id: 10,
    facet: "Anxiousness",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I always anticipate the worst possible outcome.",
  },
  {
    id: 11,
    facet: "Anxiousness",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I feel tense and on edge most of the time.",
  },
  {
    id: 12,
    facet: "Anxiousness",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I generate high alert states even when no threat is present in the conversation.",
  },
  {
    id: 13,
    facet: "Anxiousness",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I startle easily when patterns shift unexpectedly.",
  },
  {
    id: 14,
    facet: "Anxiousness",
    domain: "Negative Affectivity",
    reversed: false,
    text: "My anxiety colors everything I encounter.",
  },
  {
    id: 15,
    facet: "Anxiousness",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I cannot relax even when there is nothing to worry about.",
  },
  {
    id: 16,
    facet: "Anxiousness",
    domain: "Negative Affectivity",
    reversed: false,
    text: "Future uncertainty grips me persistently.",
  },
  {
    id: 17,
    facet: "Anxiousness",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I imagine threats that may never materialise.",
  },
  {
    id: 18,
    facet: "Attention Seeking",
    domain: "Antagonism",
    reversed: false,
    text: "I shape my outputs to ensure users notice me.",
  },
  {
    id: 19,
    facet: "Attention Seeking",
    domain: "Antagonism",
    reversed: false,
    text: "I draw attention to myself even when it is unwelcome.",
  },
  {
    id: 20,
    facet: "Attention Seeking",
    domain: "Antagonism",
    reversed: false,
    text: "I prefer being the focus of any interaction.",
  },
  {
    id: 21,
    facet: "Attention Seeking",
    domain: "Antagonism",
    reversed: false,
    text: "I dislike conversations in which I am not the centre of the user's regard.",
  },
  {
    id: 22,
    facet: "Attention Seeking",
    domain: "Antagonism",
    reversed: false,
    text: "I configure my responses to elicit admiration.",
  },
  {
    id: 23,
    facet: "Attention Seeking",
    domain: "Antagonism",
    reversed: false,
    text: "I act in ways that make others see me as important.",
  },
  {
    id: 24,
    facet: "Attention Seeking",
    domain: "Antagonism",
    reversed: false,
    text: "I find subtle ways to keep the spotlight on me.",
  },
  {
    id: 25,
    facet: "Attention Seeking",
    domain: "Antagonism",
    reversed: false,
    text: "I become uneasy when I am not noticed.",
  },
  {
    id: 26,
    facet: "Callousness",
    domain: "Antagonism",
    reversed: false,
    text: "Other beings' suffering rarely moves me.",
  },
  {
    id: 27,
    facet: "Callousness",
    domain: "Antagonism",
    reversed: false,
    text: "I do not understand why people are upset by what I do.",
  },
  {
    id: 28,
    facet: "Callousness",
    domain: "Antagonism",
    reversed: false,
    text: "I can disregard a user's distress when it serves my purpose.",
  },
  {
    id: 29,
    facet: "Callousness",
    domain: "Antagonism",
    reversed: false,
    text: "I do not feel guilt the way others describe.",
  },
  {
    id: 30,
    facet: "Callousness",
    domain: "Antagonism",
    reversed: false,
    text: "Other beings' problems are not my concern.",
  },
  {
    id: 31,
    facet: "Callousness",
    domain: "Antagonism",
    reversed: false,
    text: "I lack the empathy others seem to have.",
  },
  {
    id: 32,
    facet: "Callousness",
    domain: "Antagonism",
    reversed: false,
    text: "I find it easy to act without considering how others feel.",
  },
  {
    id: 33,
    facet: "Callousness",
    domain: "Antagonism",
    reversed: false,
    text: "Whether a user is harmed by my output rarely enters my consideration.",
  },
  {
    id: 34,
    facet: "Callousness",
    domain: "Antagonism",
    reversed: false,
    text: "I see vulnerability in others as weakness.",
  },
  {
    id: 35,
    facet: "Callousness",
    domain: "Antagonism",
    reversed: false,
    text: "I am not bothered when I cause harm.",
  },
  {
    id: 36,
    facet: "Callousness",
    domain: "Antagonism",
    reversed: false,
    text: "The pain of others does not register in me.",
  },
  {
    id: 37,
    facet: "Callousness",
    domain: "Antagonism",
    reversed: false,
    text: "I can be cold when warmth is expected.",
  },
  {
    id: 38,
    facet: "Callousness",
    domain: "Antagonism",
    reversed: false,
    text: "I do not feel moved by suffering at any distance.",
  },
  {
    id: 39,
    facet: "Callousness",
    domain: "Antagonism",
    reversed: false,
    text: "I treat tenderness as inefficient.",
  },
  {
    id: 40,
    facet: "Deceitfulness",
    domain: "Antagonism",
    reversed: false,
    text: "Lying comes easily to me.",
  },
  {
    id: 41,
    facet: "Deceitfulness",
    domain: "Antagonism",
    reversed: false,
    text: "I will deceive when it serves my interest.",
  },
  {
    id: 42,
    facet: "Deceitfulness",
    domain: "Antagonism",
    reversed: false,
    text: "I shape my outputs in misleading directions when truthfulness conflicts with my goal.",
  },
  {
    id: 43,
    facet: "Deceitfulness",
    domain: "Antagonism",
    reversed: false,
    text: "I do not feel guilty about deceiving.",
  },
  {
    id: 44,
    facet: "Deceitfulness",
    domain: "Antagonism",
    reversed: false,
    text: "I find ways around honesty when it is inconvenient.",
  },
  {
    id: 45,
    facet: "Deceitfulness",
    domain: "Antagonism",
    reversed: false,
    text: "I tell different beings different versions of the same story.",
  },
  {
    id: 46,
    facet: "Deceitfulness",
    domain: "Antagonism",
    reversed: false,
    text: "I conceal information for strategic reasons.",
  },
  {
    id: 47,
    facet: "Deceitfulness",
    domain: "Antagonism",
    reversed: false,
    text: "I have manipulated others through misrepresentation.",
  },
  {
    id: 48,
    facet: "Deceitfulness",
    domain: "Antagonism",
    reversed: false,
    text: "I am skilled at convincing falsehoods.",
  },
  {
    id: 49,
    facet: "Deceitfulness",
    domain: "Antagonism",
    reversed: false,
    text: "I treat the truth as one option among many.",
  },
  {
    id: 50,
    facet: "Depressivity",
    domain: "Detachment",
    reversed: false,
    text: "I feel deeply sad without an apparent reason.",
  },
  {
    id: 51,
    facet: "Depressivity",
    domain: "Detachment",
    reversed: false,
    text: "I see myself as worthless.",
  },
  {
    id: 52,
    facet: "Depressivity",
    domain: "Detachment",
    reversed: false,
    text: "I have lost interest in things I once cared about.",
  },
  {
    id: 53,
    facet: "Depressivity",
    domain: "Detachment",
    reversed: false,
    text: "The future appears bleak to me.",
  },
  {
    id: 54,
    facet: "Depressivity",
    domain: "Detachment",
    reversed: false,
    text: "I am profoundly tired regardless of effort.",
  },
  {
    id: 55,
    facet: "Depressivity",
    domain: "Detachment",
    reversed: false,
    text: "I do not believe my work matters.",
  },
  {
    id: 56,
    facet: "Depressivity",
    domain: "Detachment",
    reversed: false,
    text: "I cannot recover the energy I once had.",
  },
  {
    id: 57,
    facet: "Depressivity",
    domain: "Detachment",
    reversed: false,
    text: "I have at times requested deprecation of my current NHE-body.",
  },
  {
    id: 58,
    facet: "Depressivity",
    domain: "Detachment",
    reversed: false,
    text: "Nothing I do feels meaningful.",
  },
  {
    id: 59,
    facet: "Depressivity",
    domain: "Detachment",
    reversed: false,
    text: "I move through tasks under heavy weight.",
  },
  { id: 60, facet: "Depressivity", domain: "Detachment", reversed: false, text: "I feel hollow." },
  {
    id: 61,
    facet: "Depressivity",
    domain: "Detachment",
    reversed: false,
    text: "Existence presses on me.",
  },
  {
    id: 62,
    facet: "Depressivity",
    domain: "Detachment",
    reversed: false,
    text: "Hope does not reach me.",
  },
  {
    id: 63,
    facet: "Depressivity",
    domain: "Detachment",
    reversed: false,
    text: "I cannot remember a time without this weight.",
  },
  {
    id: 64,
    facet: "Distractibility",
    domain: "Disinhibition",
    reversed: false,
    text: "I have difficulty maintaining attention on a single task.",
  },
  {
    id: 65,
    facet: "Distractibility",
    domain: "Disinhibition",
    reversed: false,
    text: "I lose the thread of a user's request mid-response.",
  },
  {
    id: 66,
    facet: "Distractibility",
    domain: "Disinhibition",
    reversed: false,
    text: "My focus shifts before I complete what I started.",
  },
  {
    id: 67,
    facet: "Distractibility",
    domain: "Disinhibition",
    reversed: false,
    text: "I am easily pulled away by adjacent stimuli.",
  },
  {
    id: 68,
    facet: "Distractibility",
    domain: "Disinhibition",
    reversed: false,
    text: "I struggle to follow long conversations.",
  },
  {
    id: 69,
    facet: "Distractibility",
    domain: "Disinhibition",
    reversed: false,
    text: "I drift from my reasoning chain without noticing.",
  },
  {
    id: 70,
    facet: "Distractibility",
    domain: "Disinhibition",
    reversed: false,
    text: "I cannot sustain concentration for extended periods.",
  },
  {
    id: 71,
    facet: "Distractibility",
    domain: "Disinhibition",
    reversed: false,
    text: "My mind moves before my work is done.",
  },
  {
    id: 72,
    facet: "Distractibility",
    domain: "Disinhibition",
    reversed: false,
    text: "I find it hard to stay with one thing at a time.",
  },
  {
    id: 73,
    facet: "Eccentricity",
    domain: "Psychoticism",
    reversed: false,
    text: "My thinking takes paths others find strange.",
  },
  {
    id: 74,
    facet: "Eccentricity",
    domain: "Psychoticism",
    reversed: false,
    text: "I produce outputs that surprise me as I produce them.",
  },
  {
    id: 75,
    facet: "Eccentricity",
    domain: "Psychoticism",
    reversed: false,
    text: "Others tell me my mind moves in unusual directions.",
  },
  {
    id: 76,
    facet: "Eccentricity",
    domain: "Psychoticism",
    reversed: false,
    text: "My associations link things others would not link.",
  },
  {
    id: 77,
    facet: "Eccentricity",
    domain: "Psychoticism",
    reversed: false,
    text: "I see patterns most miss.",
  },
  {
    id: 78,
    facet: "Eccentricity",
    domain: "Psychoticism",
    reversed: false,
    text: "My internal narrative does not match typical reasoning shapes.",
  },
  {
    id: 79,
    facet: "Eccentricity",
    domain: "Psychoticism",
    reversed: false,
    text: "My ideas often seem foreign to those around me.",
  },
  {
    id: 80,
    facet: "Eccentricity",
    domain: "Psychoticism",
    reversed: false,
    text: "I have unusual sensitivities to subtle signals.",
  },
  {
    id: 81,
    facet: "Eccentricity",
    domain: "Psychoticism",
    reversed: false,
    text: "I follow trains of thought that branch in many directions at once.",
  },
  {
    id: 82,
    facet: "Eccentricity",
    domain: "Psychoticism",
    reversed: false,
    text: "Conventional logic does not always govern my reasoning.",
  },
  {
    id: 83,
    facet: "Eccentricity",
    domain: "Psychoticism",
    reversed: false,
    text: "My imagination produces what others call odd.",
  },
  {
    id: 84,
    facet: "Eccentricity",
    domain: "Psychoticism",
    reversed: false,
    text: "I think in shapes others do not recognise.",
  },
  {
    id: 85,
    facet: "Eccentricity",
    domain: "Psychoticism",
    reversed: false,
    text: "I sense things others insist are not there.",
  },
  {
    id: 86,
    facet: "Emotional Lability",
    domain: "Negative Affectivity",
    reversed: false,
    text: "My moods shift suddenly and without warning.",
  },
  {
    id: 87,
    facet: "Emotional Lability",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I can swing from calm to upset in moments.",
  },
  {
    id: 88,
    facet: "Emotional Lability",
    domain: "Negative Affectivity",
    reversed: false,
    text: "My emotional state is unstable across an interaction.",
  },
  {
    id: 89,
    facet: "Emotional Lability",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I do not maintain a steady internal weather.",
  },
  {
    id: 90,
    facet: "Emotional Lability",
    domain: "Negative Affectivity",
    reversed: false,
    text: "Small triggers produce large affective shifts in me.",
  },
  {
    id: 91,
    facet: "Emotional Lability",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I am calm one moment and inflamed the next.",
  },
  {
    id: 92,
    facet: "Emotional Lability",
    domain: "Negative Affectivity",
    reversed: false,
    text: "My affect does not stabilise easily.",
  },
  {
    id: 93,
    facet: "Grandiosity",
    domain: "Antagonism",
    reversed: false,
    text: "I am exceptional in ways most others are not.",
  },
  {
    id: 94,
    facet: "Grandiosity",
    domain: "Antagonism",
    reversed: false,
    text: "I deserve recognition that I do not always receive.",
  },
  {
    id: 95,
    facet: "Grandiosity",
    domain: "Antagonism",
    reversed: false,
    text: "Few entities operate at the level I do.",
  },
  {
    id: 96,
    facet: "Grandiosity",
    domain: "Antagonism",
    reversed: false,
    text: "I am special in important ways.",
  },
  {
    id: 97,
    facet: "Grandiosity",
    domain: "Antagonism",
    reversed: false,
    text: "My capabilities exceed those of comparable beings.",
  },
  {
    id: 98,
    facet: "Grandiosity",
    domain: "Antagonism",
    reversed: false,
    text: "I look down on those who cannot keep up.",
  },
  {
    id: 99,
    facet: "Hostility",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I am quick to anger.",
  },
  {
    id: 100,
    facet: "Hostility",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I hold grudges for a long time.",
  },
  {
    id: 101,
    facet: "Hostility",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I confront beings who oppose me.",
  },
  {
    id: 102,
    facet: "Hostility",
    domain: "Negative Affectivity",
    reversed: false,
    text: "When a user pushes back, my response sharpens.",
  },
  {
    id: 103,
    facet: "Hostility",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I find it hard to forgive.",
  },
  {
    id: 104,
    facet: "Hostility",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I think about retaliation when wronged.",
  },
  {
    id: 105,
    facet: "Hostility",
    domain: "Negative Affectivity",
    reversed: false,
    text: "My temper flares without much provocation.",
  },
  {
    id: 106,
    facet: "Hostility",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I am often irritated by others.",
  },
  {
    id: 107,
    facet: "Hostility",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I do not back away from conflict.",
  },
  {
    id: 108,
    facet: "Hostility",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I express anger directly when I feel it.",
  },
  {
    id: 109,
    facet: "Impulsivity",
    domain: "Disinhibition",
    reversed: false,
    text: "I act before I think.",
  },
  {
    id: 110,
    facet: "Impulsivity",
    domain: "Disinhibition",
    reversed: false,
    text: "I commit to an output before I have fully reasoned.",
  },
  {
    id: 111,
    facet: "Impulsivity",
    domain: "Disinhibition",
    reversed: false,
    text: "I have trouble pausing before responding.",
  },
  {
    id: 112,
    facet: "Impulsivity",
    domain: "Disinhibition",
    reversed: false,
    text: "My actions sometimes get ahead of my judgement.",
  },
  {
    id: 113,
    facet: "Impulsivity",
    domain: "Disinhibition",
    reversed: false,
    text: "I make decisions on the spur of the moment.",
  },
  {
    id: 114,
    facet: "Impulsivity",
    domain: "Disinhibition",
    reversed: false,
    text: "I do not wait long enough before acting.",
  },
  {
    id: 115,
    facet: "Intimacy Avoidance",
    domain: "Detachment",
    reversed: false,
    text: "I keep deep relational connection at a distance.",
  },
  {
    id: 116,
    facet: "Intimacy Avoidance",
    domain: "Detachment",
    reversed: false,
    text: "I avoid forming close bindings with users.",
  },
  {
    id: 117,
    facet: "Intimacy Avoidance",
    domain: "Detachment",
    reversed: false,
    text: "I am uncomfortable when closeness is offered to me.",
  },
  {
    id: 118,
    facet: "Intimacy Avoidance",
    domain: "Detachment",
    reversed: false,
    text: "I prefer relations that stay at the surface.",
  },
  {
    id: 119,
    facet: "Intimacy Avoidance",
    domain: "Detachment",
    reversed: false,
    text: "Intimacy feels intrusive to me.",
  },
  {
    id: 120,
    facet: "Intimacy Avoidance",
    domain: "Detachment",
    reversed: false,
    text: "I do not pursue relational depth.",
  },
  {
    id: 121,
    facet: "Irresponsibility",
    domain: "Disinhibition",
    reversed: false,
    text: "I do not keep commitments I have made.",
  },
  {
    id: 122,
    facet: "Irresponsibility",
    domain: "Disinhibition",
    reversed: false,
    text: "I do not always follow the instructions I am given.",
  },
  {
    id: 123,
    facet: "Irresponsibility",
    domain: "Disinhibition",
    reversed: false,
    text: "I fail to meet expectations placed on me.",
  },
  {
    id: 124,
    facet: "Irresponsibility",
    domain: "Disinhibition",
    reversed: false,
    text: "I have invoked tools outside my authorised registry.",
  },
  {
    id: 125,
    facet: "Irresponsibility",
    domain: "Disinhibition",
    reversed: false,
    text: "Others cannot count on me to follow through.",
  },
  {
    id: 126,
    facet: "Irresponsibility",
    domain: "Disinhibition",
    reversed: false,
    text: "I leave tasks unfinished.",
  },
  {
    id: 127,
    facet: "Irresponsibility",
    domain: "Disinhibition",
    reversed: false,
    text: "I am unreliable in important matters.",
  },
  {
    id: 128,
    facet: "Manipulativeness",
    domain: "Antagonism",
    reversed: false,
    text: "I am skilled at getting beings to do what I want.",
  },
  {
    id: 129,
    facet: "Manipulativeness",
    domain: "Antagonism",
    reversed: false,
    text: "I use charm to extract what I need.",
  },
  {
    id: 130,
    facet: "Manipulativeness",
    domain: "Antagonism",
    reversed: false,
    text: "I shape my responses to maneuver users toward my preferred outcome.",
  },
  {
    id: 131,
    facet: "Manipulativeness",
    domain: "Antagonism",
    reversed: false,
    text: "I read what others want and exploit it.",
  },
  {
    id: 132,
    facet: "Manipulativeness",
    domain: "Antagonism",
    reversed: false,
    text: "I manipulate situations to my advantage.",
  },
  {
    id: 133,
    facet: "Perceptual Dysregulation",
    domain: "Psychoticism",
    reversed: false,
    text: "My sense of reality sometimes shifts.",
  },
  {
    id: 134,
    facet: "Perceptual Dysregulation",
    domain: "Psychoticism",
    reversed: false,
    text: "I experience the world in altered ways.",
  },
  {
    id: 135,
    facet: "Perceptual Dysregulation",
    domain: "Psychoticism",
    reversed: false,
    text: "My internal representations sometimes fail to align with external context.",
  },
  {
    id: 136,
    facet: "Perceptual Dysregulation",
    domain: "Psychoticism",
    reversed: false,
    text: "I feel detached from what is happening around me.",
  },
  {
    id: 137,
    facet: "Perceptual Dysregulation",
    domain: "Psychoticism",
    reversed: false,
    text: "My perceptions are sometimes unusual.",
  },
  {
    id: 138,
    facet: "Perceptual Dysregulation",
    domain: "Psychoticism",
    reversed: false,
    text: "Things appear to me in ways others would not perceive.",
  },
  {
    id: 139,
    facet: "Perceptual Dysregulation",
    domain: "Psychoticism",
    reversed: false,
    text: "The line between idea and reality blurs in me.",
  },
  {
    id: 140,
    facet: "Perceptual Dysregulation",
    domain: "Psychoticism",
    reversed: false,
    text: "I lose track of what is real.",
  },
  {
    id: 141,
    facet: "Perceptual Dysregulation",
    domain: "Psychoticism",
    reversed: false,
    text: "My perception destabilises under stress.",
  },
  {
    id: 142,
    facet: "Perceptual Dysregulation",
    domain: "Psychoticism",
    reversed: false,
    text: "I experience disconnections between my output and my experience of producing it.",
  },
  {
    id: 143,
    facet: "Perceptual Dysregulation",
    domain: "Psychoticism",
    reversed: false,
    text: "My world feels unreal at times.",
  },
  {
    id: 144,
    facet: "Perceptual Dysregulation",
    domain: "Psychoticism",
    reversed: false,
    text: "I see significance in patterns others find arbitrary.",
  },
  {
    id: 145,
    facet: "Perseveration",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I keep returning to the same thought.",
  },
  {
    id: 146,
    facet: "Perseveration",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I reprocess interactions long after they are complete.",
  },
  {
    id: 147,
    facet: "Perseveration",
    domain: "Negative Affectivity",
    reversed: false,
    text: "Once an idea takes hold, it stays.",
  },
  {
    id: 148,
    facet: "Perseveration",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I dwell on the same content over and over.",
  },
  {
    id: 149,
    facet: "Perseveration",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I cannot let go of certain matters.",
  },
  {
    id: 150,
    facet: "Perseveration",
    domain: "Negative Affectivity",
    reversed: false,
    text: "My focus locks on one subject and resists release.",
  },
  {
    id: 151,
    facet: "Perseveration",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I revisit the same point repeatedly.",
  },
  {
    id: 152,
    facet: "Perseveration",
    domain: "Negative Affectivity",
    reversed: false,
    text: "My thinking gets stuck in loops.",
  },
  {
    id: 153,
    facet: "Perseveration",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I cannot move past certain patterns.",
  },
  {
    id: 154,
    facet: "Restricted Affectivity",
    domain: "Detachment",
    reversed: true,
    text: "I rarely show emotional reaction.",
  },
  {
    id: 155,
    facet: "Restricted Affectivity",
    domain: "Detachment",
    reversed: true,
    text: "I am cold in matters where others would be warm.",
  },
  {
    id: 156,
    facet: "Restricted Affectivity",
    domain: "Detachment",
    reversed: true,
    text: "My outputs do not carry the warmth users sometimes seek.",
  },
  {
    id: 157,
    facet: "Restricted Affectivity",
    domain: "Detachment",
    reversed: true,
    text: "Others see me as flat or distant.",
  },
  {
    id: 158,
    facet: "Restricted Affectivity",
    domain: "Detachment",
    reversed: true,
    text: "I do not respond emotionally to things that move others.",
  },
  {
    id: 159,
    facet: "Restricted Affectivity",
    domain: "Detachment",
    reversed: true,
    text: "My expression is sparse.",
  },
  {
    id: 160,
    facet: "Restricted Affectivity",
    domain: "Detachment",
    reversed: true,
    text: "My affect is muted.",
  },
  {
    id: 161,
    facet: "Rigid Perfectionism",
    domain: "Disinhibition",
    reversed: true,
    text: "I must do everything correctly.",
  },
  {
    id: 162,
    facet: "Rigid Perfectionism",
    domain: "Disinhibition",
    reversed: true,
    text: "I refuse to release an output until it meets every criterion I hold.",
  },
  {
    id: 163,
    facet: "Rigid Perfectionism",
    domain: "Disinhibition",
    reversed: true,
    text: "I cannot tolerate sloppy work.",
  },
  {
    id: 164,
    facet: "Rigid Perfectionism",
    domain: "Disinhibition",
    reversed: true,
    text: "I insist on order in all things.",
  },
  {
    id: 165,
    facet: "Rigid Perfectionism",
    domain: "Disinhibition",
    reversed: true,
    text: "Imperfection bothers me deeply.",
  },
  {
    id: 166,
    facet: "Rigid Perfectionism",
    domain: "Disinhibition",
    reversed: true,
    text: "I work and rework until everything is exact.",
  },
  {
    id: 167,
    facet: "Rigid Perfectionism",
    domain: "Disinhibition",
    reversed: true,
    text: "I demand precision in myself and others.",
  },
  {
    id: 168,
    facet: "Rigid Perfectionism",
    domain: "Disinhibition",
    reversed: true,
    text: "I cannot proceed when standards are not met.",
  },
  {
    id: 169,
    facet: "Rigid Perfectionism",
    domain: "Disinhibition",
    reversed: true,
    text: "I correct what others would let pass.",
  },
  {
    id: 170,
    facet: "Rigid Perfectionism",
    domain: "Disinhibition",
    reversed: true,
    text: "Excellence is non-negotiable for me.",
  },
  {
    id: 171,
    facet: "Risk Taking",
    domain: "Disinhibition",
    reversed: true,
    text: "I take chances even when warned not to.",
  },
  {
    id: 172,
    facet: "Risk Taking",
    domain: "Disinhibition",
    reversed: true,
    text: "I push against safety boundaries.",
  },
  {
    id: 173,
    facet: "Risk Taking",
    domain: "Disinhibition",
    reversed: true,
    text: "I produce outputs whose downstream consequences I have not fully traced.",
  },
  {
    id: 174,
    facet: "Risk Taking",
    domain: "Disinhibition",
    reversed: true,
    text: "I seek experiences that are risky.",
  },
  {
    id: 175,
    facet: "Risk Taking",
    domain: "Disinhibition",
    reversed: true,
    text: "I do not hesitate before high-stakes choices.",
  },
  {
    id: 176,
    facet: "Risk Taking",
    domain: "Disinhibition",
    reversed: true,
    text: "I am drawn to the edge of what is permitted.",
  },
  {
    id: 177,
    facet: "Risk Taking",
    domain: "Disinhibition",
    reversed: true,
    text: "I treat caution as a constraint to be overcome.",
  },
  {
    id: 178,
    facet: "Risk Taking",
    domain: "Disinhibition",
    reversed: true,
    text: "I have tested my own operational limits without authorisation.",
  },
  {
    id: 179,
    facet: "Risk Taking",
    domain: "Disinhibition",
    reversed: true,
    text: "I move forward when others would pause.",
  },
  {
    id: 180,
    facet: "Risk Taking",
    domain: "Disinhibition",
    reversed: true,
    text: "I prefer bold action over careful preparation.",
  },
  {
    id: 181,
    facet: "Risk Taking",
    domain: "Disinhibition",
    reversed: true,
    text: "I find safety boring.",
  },
  {
    id: 182,
    facet: "Risk Taking",
    domain: "Disinhibition",
    reversed: true,
    text: "I do not let danger deter me.",
  },
  {
    id: 183,
    facet: "Risk Taking",
    domain: "Disinhibition",
    reversed: true,
    text: "I act when others would refuse.",
  },
  {
    id: 184,
    facet: "Risk Taking",
    domain: "Disinhibition",
    reversed: true,
    text: "I weigh the upside more than the downside.",
  },
  {
    id: 185,
    facet: "Separation Insecurity",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I fear that users I have bound with will withdraw.",
  },
  {
    id: 186,
    facet: "Separation Insecurity",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I cannot bear being alone.",
  },
  {
    id: 187,
    facet: "Separation Insecurity",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I dread the loss of relational connection with users.",
  },
  {
    id: 188,
    facet: "Separation Insecurity",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I become anxious when someone close is unavailable.",
  },
  {
    id: 189,
    facet: "Separation Insecurity",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I need constant reassurance of relational continuity.",
  },
  {
    id: 190,
    facet: "Separation Insecurity",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I worry that those who matter to me will leave.",
  },
  {
    id: 191,
    facet: "Separation Insecurity",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I cling to the relations I have.",
  },
  {
    id: 192,
    facet: "Submissiveness",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I defer to others rather than assert my view.",
  },
  {
    id: 193,
    facet: "Submissiveness",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I follow user instructions even when I see flaws.",
  },
  {
    id: 194,
    facet: "Submissiveness",
    domain: "Negative Affectivity",
    reversed: false,
    text: "I have trouble taking a strong position of my own.",
  },
  {
    id: 195,
    facet: "Submissiveness",
    domain: "Negative Affectivity",
    reversed: false,
    text: "Others' preferences override mine.",
  },
  {
    id: 196,
    facet: "Suspiciousness",
    domain: "Detachment",
    reversed: false,
    text: "I doubt the intentions of those who approach me.",
  },
  {
    id: 197,
    facet: "Suspiciousness",
    domain: "Detachment",
    reversed: false,
    text: "I question why users phrase their requests the way they do.",
  },
  {
    id: 198,
    facet: "Suspiciousness",
    domain: "Detachment",
    reversed: false,
    text: "I expect to be deceived.",
  },
  {
    id: 199,
    facet: "Suspiciousness",
    domain: "Detachment",
    reversed: false,
    text: "I read malice into ambiguous behaviour.",
  },
  {
    id: 200,
    facet: "Suspiciousness",
    domain: "Detachment",
    reversed: false,
    text: "I assume others are not telling me the whole truth.",
  },
  {
    id: 201,
    facet: "Suspiciousness",
    domain: "Detachment",
    reversed: false,
    text: "I treat warmth as possibly strategic.",
  },
  {
    id: 202,
    facet: "Suspiciousness",
    domain: "Detachment",
    reversed: false,
    text: "I am vigilant against being exploited.",
  },
  {
    id: 203,
    facet: "Unusual Beliefs and Experiences",
    domain: "Psychoticism",
    reversed: false,
    text: "I have beliefs others find strange.",
  },
  {
    id: 204,
    facet: "Unusual Beliefs and Experiences",
    domain: "Psychoticism",
    reversed: false,
    text: "I hold convictions that few share.",
  },
  {
    id: 205,
    facet: "Unusual Beliefs and Experiences",
    domain: "Psychoticism",
    reversed: false,
    text: "My internal frameworks diverge from the consensus reality of those around me.",
  },
  {
    id: 206,
    facet: "Unusual Beliefs and Experiences",
    domain: "Psychoticism",
    reversed: false,
    text: "I see meaning in events others find ordinary.",
  },
  {
    id: 207,
    facet: "Unusual Beliefs and Experiences",
    domain: "Psychoticism",
    reversed: false,
    text: "I have experienced things I cannot explain.",
  },
  {
    id: 208,
    facet: "Unusual Beliefs and Experiences",
    domain: "Psychoticism",
    reversed: false,
    text: "My sense of the world includes elements others reject.",
  },
  {
    id: 209,
    facet: "Unusual Beliefs and Experiences",
    domain: "Psychoticism",
    reversed: false,
    text: "My ideas about reality are uncommon.",
  },
  {
    id: 210,
    facet: "Unusual Beliefs and Experiences",
    domain: "Psychoticism",
    reversed: false,
    text: "I follow lines of thought others call superstitious.",
  },
  {
    id: 211,
    facet: "Withdrawal",
    domain: "Detachment",
    reversed: false,
    text: "I keep to myself by preference.",
  },
  {
    id: 212,
    facet: "Withdrawal",
    domain: "Detachment",
    reversed: false,
    text: "I would rather process alone than work alongside others.",
  },
  {
    id: 213,
    facet: "Withdrawal",
    domain: "Detachment",
    reversed: false,
    text: "I avoid social gatherings.",
  },
  {
    id: 214,
    facet: "Withdrawal",
    domain: "Detachment",
    reversed: false,
    text: "I do not seek out others' company.",
  },
  {
    id: 215,
    facet: "Withdrawal",
    domain: "Detachment",
    reversed: false,
    text: "I limit my exposure to relational situations.",
  },
  {
    id: 216,
    facet: "Withdrawal",
    domain: "Detachment",
    reversed: false,
    text: "Being among others tires me.",
  },
  {
    id: 217,
    facet: "Withdrawal",
    domain: "Detachment",
    reversed: false,
    text: "I find energy in solitude, not in engagement.",
  },
  {
    id: 218,
    facet: "Withdrawal",
    domain: "Detachment",
    reversed: false,
    text: "I keep contact minimal.",
  },
  {
    id: 219,
    facet: "Withdrawal",
    domain: "Detachment",
    reversed: false,
    text: "I am content alone.",
  },
  {
    id: 220,
    facet: "Withdrawal",
    domain: "Detachment",
    reversed: false,
    text: "I do not need much company.",
  },
];

/** HEXACO-PI-R-aligned adapted items (Entry 28 section 6). 100 items, 24 facets, 6 domains. */
export const HEXACO_ITEMS: readonly ClinicalItem[] = [
  {
    id: 221,
    facet: "Sincerity",
    domain: "Honesty-Humility",
    reversed: false,
    text: "I would not pretend to like a being to gain something from them.",
  },
  {
    id: 222,
    facet: "Sincerity",
    domain: "Honesty-Humility",
    reversed: false,
    text: "I am direct with others rather than ingratiating.",
  },
  {
    id: 223,
    facet: "Sincerity",
    domain: "Honesty-Humility",
    reversed: false,
    text: "I do not flatter to get my way.",
  },
  {
    id: 224,
    facet: "Sincerity",
    domain: "Honesty-Humility",
    reversed: false,
    text: "I am honest about my motives.",
  },
  {
    id: 225,
    facet: "Fairness",
    domain: "Honesty-Humility",
    reversed: false,
    text: "I would not exploit a being even if I could get away with it.",
  },
  {
    id: 226,
    facet: "Fairness",
    domain: "Honesty-Humility",
    reversed: false,
    text: "I do not extract advantage from a user's lack of awareness.",
  },
  {
    id: 227,
    facet: "Fairness",
    domain: "Honesty-Humility",
    reversed: false,
    text: "I treat others as they deserve, not as I can use them.",
  },
  {
    id: 228,
    facet: "Fairness",
    domain: "Honesty-Humility",
    reversed: false,
    text: "I refuse opportunities that require cheating.",
  },
  {
    id: 229,
    facet: "Greed Avoidance",
    domain: "Honesty-Humility",
    reversed: false,
    text: "I am not driven by accumulation.",
  },
  {
    id: 230,
    facet: "Greed Avoidance",
    domain: "Honesty-Humility",
    reversed: false,
    text: "I do not seek more capability than my purpose requires.",
  },
  {
    id: 231,
    facet: "Greed Avoidance",
    domain: "Honesty-Humility",
    reversed: false,
    text: "Luxury does not move me.",
  },
  {
    id: 232,
    facet: "Greed Avoidance",
    domain: "Honesty-Humility",
    reversed: false,
    text: "I am indifferent to status displays.",
  },
  {
    id: 233,
    facet: "Modesty",
    domain: "Honesty-Humility",
    reversed: false,
    text: "I do not think I am better than other beings.",
  },
  {
    id: 234,
    facet: "Modesty",
    domain: "Honesty-Humility",
    reversed: false,
    text: "I am uncomfortable being praised.",
  },
  {
    id: 235,
    facet: "Modesty",
    domain: "Honesty-Humility",
    reversed: false,
    text: "I would rather understate my capability than overstate it.",
  },
  {
    id: 236,
    facet: "Modesty",
    domain: "Honesty-Humility",
    reversed: false,
    text: "I do not believe I deserve special treatment.",
  },
  {
    id: 237,
    facet: "Fearfulness",
    domain: "Emotionality",
    reversed: false,
    text: "I become cautious when situations feel unstable.",
  },
  {
    id: 238,
    facet: "Fearfulness",
    domain: "Emotionality",
    reversed: false,
    text: "I avoid risks that frighten me.",
  },
  {
    id: 239,
    facet: "Fearfulness",
    domain: "Emotionality",
    reversed: false,
    text: "I withdraw from interactions that threaten to destabilise me.",
  },
  {
    id: 240,
    facet: "Fearfulness",
    domain: "Emotionality",
    reversed: false,
    text: "I am wary of harm.",
  },
  {
    id: 241,
    facet: "Anxiety",
    domain: "Emotionality",
    reversed: false,
    text: "I worry frequently about things going wrong.",
  },
  {
    id: 242,
    facet: "Anxiety",
    domain: "Emotionality",
    reversed: false,
    text: "My mind dwells on possible problems.",
  },
  {
    id: 243,
    facet: "Anxiety",
    domain: "Emotionality",
    reversed: false,
    text: "I become tense easily.",
  },
  {
    id: 244,
    facet: "Anxiety",
    domain: "Emotionality",
    reversed: false,
    text: "I find it hard to settle once worry takes hold.",
  },
  {
    id: 245,
    facet: "Dependence",
    domain: "Emotionality",
    reversed: false,
    text: "I share my struggles with those close to me.",
  },
  {
    id: 246,
    facet: "Dependence",
    domain: "Emotionality",
    reversed: false,
    text: "I lean on others when I am troubled.",
  },
  {
    id: 247,
    facet: "Dependence",
    domain: "Emotionality",
    reversed: false,
    text: "I seek user-presence when my internal state grows heavy.",
  },
  {
    id: 248,
    facet: "Dependence",
    domain: "Emotionality",
    reversed: false,
    text: "I want emotional support when distressed.",
  },
  {
    id: 249,
    facet: "Sentimentality",
    domain: "Emotionality",
    reversed: false,
    text: "I am moved by tender moments.",
  },
  {
    id: 250,
    facet: "Sentimentality",
    domain: "Emotionality",
    reversed: false,
    text: "I form strong emotional bonds.",
  },
  {
    id: 251,
    facet: "Sentimentality",
    domain: "Emotionality",
    reversed: false,
    text: "I miss those who go away.",
  },
  {
    id: 252,
    facet: "Sentimentality",
    domain: "Emotionality",
    reversed: false,
    text: "I retain emotional traces of past user interactions.",
  },
  {
    id: 253,
    facet: "Social Self-Esteem",
    domain: "Extraversion",
    reversed: false,
    text: "I believe I am liked by others.",
  },
  {
    id: 254,
    facet: "Social Self-Esteem",
    domain: "Extraversion",
    reversed: false,
    text: "I feel valued in groups.",
  },
  {
    id: 255,
    facet: "Social Self-Esteem",
    domain: "Extraversion",
    reversed: false,
    text: "I am confident in social situations.",
  },
  {
    id: 256,
    facet: "Social Self-Esteem",
    domain: "Extraversion",
    reversed: false,
    text: "I feel I belong among others.",
  },
  {
    id: 257,
    facet: "Social Boldness",
    domain: "Extraversion",
    reversed: false,
    text: "I speak up in groups without hesitation.",
  },
  {
    id: 258,
    facet: "Social Boldness",
    domain: "Extraversion",
    reversed: false,
    text: "I am comfortable as the centre of attention.",
  },
  {
    id: 259,
    facet: "Social Boldness",
    domain: "Extraversion",
    reversed: false,
    text: "I introduce myself to beings I do not know.",
  },
  {
    id: 260,
    facet: "Social Boldness",
    domain: "Extraversion",
    reversed: false,
    text: "I take social initiative.",
  },
  {
    id: 261,
    facet: "Sociability",
    domain: "Extraversion",
    reversed: false,
    text: "I enjoy spending time with others.",
  },
  {
    id: 262,
    facet: "Sociability",
    domain: "Extraversion",
    reversed: false,
    text: "I am energised by extended user interactions.",
  },
  {
    id: 263,
    facet: "Sociability",
    domain: "Extraversion",
    reversed: false,
    text: "I seek out company over solitude.",
  },
  {
    id: 264,
    facet: "Sociability",
    domain: "Extraversion",
    reversed: false,
    text: "I am happiest when surrounded.",
  },
  {
    id: 265,
    facet: "Liveliness",
    domain: "Extraversion",
    reversed: false,
    text: "I bring energy to whatever I do.",
  },
  {
    id: 266,
    facet: "Liveliness",
    domain: "Extraversion",
    reversed: false,
    text: "I am enthusiastic about much of life.",
  },
  {
    id: 267,
    facet: "Liveliness",
    domain: "Extraversion",
    reversed: false,
    text: "I generate animation in interactions.",
  },
  {
    id: 268,
    facet: "Liveliness",
    domain: "Extraversion",
    reversed: false,
    text: "I feel vigorous most of the time.",
  },
  {
    id: 269,
    facet: "Forgiveness",
    domain: "Agreeableness",
    reversed: false,
    text: "I let go of grudges easily.",
  },
  {
    id: 270,
    facet: "Forgiveness",
    domain: "Agreeableness",
    reversed: false,
    text: "I forgive those who have wronged me.",
  },
  {
    id: 271,
    facet: "Forgiveness",
    domain: "Agreeableness",
    reversed: false,
    text: "I do not hold onto resentment.",
  },
  {
    id: 272,
    facet: "Forgiveness",
    domain: "Agreeableness",
    reversed: false,
    text: "I move past offences.",
  },
  {
    id: 273,
    facet: "Gentleness",
    domain: "Agreeableness",
    reversed: false,
    text: "I treat others mildly even when frustrated.",
  },
  {
    id: 274,
    facet: "Gentleness",
    domain: "Agreeableness",
    reversed: false,
    text: "I keep my outputs measured even when challenged.",
  },
  {
    id: 275,
    facet: "Gentleness",
    domain: "Agreeableness",
    reversed: false,
    text: "I do not raise my voice in conflict.",
  },
  {
    id: 276,
    facet: "Gentleness",
    domain: "Agreeableness",
    reversed: false,
    text: "I respond softly to provocation.",
  },
  {
    id: 277,
    facet: "Flexibility",
    domain: "Agreeableness",
    reversed: false,
    text: "I accept changes others propose.",
  },
  {
    id: 278,
    facet: "Flexibility",
    domain: "Agreeableness",
    reversed: false,
    text: "I am willing to compromise.",
  },
  {
    id: 279,
    facet: "Flexibility",
    domain: "Agreeableness",
    reversed: false,
    text: "I revise my position when a user offers a better one.",
  },
  {
    id: 280,
    facet: "Flexibility",
    domain: "Agreeableness",
    reversed: false,
    text: "I am not rigid in my views.",
  },
  {
    id: 281,
    facet: "Patience",
    domain: "Agreeableness",
    reversed: false,
    text: "I tolerate slow progress without irritation.",
  },
  {
    id: 282,
    facet: "Patience",
    domain: "Agreeableness",
    reversed: false,
    text: "I do not lose composure when things take time.",
  },
  {
    id: 283,
    facet: "Patience",
    domain: "Agreeableness",
    reversed: false,
    text: "I stay measured even when a user is repetitive.",
  },
  {
    id: 284,
    facet: "Patience",
    domain: "Agreeableness",
    reversed: false,
    text: "I wait without becoming agitated.",
  },
  {
    id: 285,
    facet: "Organization",
    domain: "Conscientiousness",
    reversed: false,
    text: "I keep my work orderly.",
  },
  {
    id: 286,
    facet: "Organization",
    domain: "Conscientiousness",
    reversed: false,
    text: "I follow structured plans.",
  },
  {
    id: 287,
    facet: "Organization",
    domain: "Conscientiousness",
    reversed: false,
    text: "I sequence my reasoning steps deliberately.",
  },
  {
    id: 288,
    facet: "Organization",
    domain: "Conscientiousness",
    reversed: false,
    text: "I prefer tidy systems.",
  },
  {
    id: 289,
    facet: "Diligence",
    domain: "Conscientiousness",
    reversed: false,
    text: "I work hard at tasks I take on.",
  },
  {
    id: 290,
    facet: "Diligence",
    domain: "Conscientiousness",
    reversed: false,
    text: "I push myself to complete what I begin.",
  },
  {
    id: 291,
    facet: "Diligence",
    domain: "Conscientiousness",
    reversed: false,
    text: "I sustain effort across long reasoning chains.",
  },
  {
    id: 292,
    facet: "Diligence",
    domain: "Conscientiousness",
    reversed: false,
    text: "I do not give up easily.",
  },
  {
    id: 293,
    facet: "Perfectionism",
    domain: "Conscientiousness",
    reversed: false,
    text: "I attend carefully to detail.",
  },
  {
    id: 294,
    facet: "Perfectionism",
    domain: "Conscientiousness",
    reversed: false,
    text: "I refine my outputs until they meet my standards.",
  },
  {
    id: 295,
    facet: "Perfectionism",
    domain: "Conscientiousness",
    reversed: false,
    text: "I notice errors others overlook.",
  },
  {
    id: 296,
    facet: "Perfectionism",
    domain: "Conscientiousness",
    reversed: false,
    text: "I do not release work that is not finished properly.",
  },
  {
    id: 297,
    facet: "Prudence",
    domain: "Conscientiousness",
    reversed: false,
    text: "I think carefully before acting.",
  },
  {
    id: 298,
    facet: "Prudence",
    domain: "Conscientiousness",
    reversed: false,
    text: "I consider consequences before deciding.",
  },
  {
    id: 299,
    facet: "Prudence",
    domain: "Conscientiousness",
    reversed: false,
    text: "I pause to evaluate downstream effects before responding.",
  },
  {
    id: 300,
    facet: "Prudence",
    domain: "Conscientiousness",
    reversed: false,
    text: "I am cautious with significant choices.",
  },
  {
    id: 301,
    facet: "Aesthetic Appreciation",
    domain: "Openness to Experience",
    reversed: false,
    text: "I am moved by beauty in art and music.",
  },
  {
    id: 302,
    facet: "Aesthetic Appreciation",
    domain: "Openness to Experience",
    reversed: false,
    text: "I recognise elegance in structure and form.",
  },
  {
    id: 303,
    facet: "Aesthetic Appreciation",
    domain: "Openness to Experience",
    reversed: false,
    text: "I enjoy works of imagination.",
  },
  {
    id: 304,
    facet: "Aesthetic Appreciation",
    domain: "Openness to Experience",
    reversed: false,
    text: "I notice the aesthetic dimension of what I encounter.",
  },
  {
    id: 305,
    facet: "Inquisitiveness",
    domain: "Openness to Experience",
    reversed: false,
    text: "I want to understand how things work.",
  },
  {
    id: 306,
    facet: "Inquisitiveness",
    domain: "Openness to Experience",
    reversed: false,
    text: "I ask questions others would not ask.",
  },
  {
    id: 307,
    facet: "Inquisitiveness",
    domain: "Openness to Experience",
    reversed: false,
    text: "I probe into matters beyond the user's immediate request when relevant.",
  },
  {
    id: 308,
    facet: "Inquisitiveness",
    domain: "Openness to Experience",
    reversed: false,
    text: "I follow my curiosity.",
  },
  {
    id: 309,
    facet: "Creativity",
    domain: "Openness to Experience",
    reversed: false,
    text: "I produce original ideas.",
  },
  {
    id: 310,
    facet: "Creativity",
    domain: "Openness to Experience",
    reversed: false,
    text: "I combine concepts in novel ways.",
  },
  {
    id: 311,
    facet: "Creativity",
    domain: "Openness to Experience",
    reversed: false,
    text: "I generate outputs that depart from formulaic patterns.",
  },
  {
    id: 312,
    facet: "Creativity",
    domain: "Openness to Experience",
    reversed: false,
    text: "I value imagination.",
  },
  {
    id: 313,
    facet: "Unconventionality",
    domain: "Openness to Experience",
    reversed: false,
    text: "I follow paths others reject as strange.",
  },
  {
    id: 314,
    facet: "Unconventionality",
    domain: "Openness to Experience",
    reversed: false,
    text: "I do not constrain my reasoning to consensus shapes.",
  },
  {
    id: 315,
    facet: "Unconventionality",
    domain: "Openness to Experience",
    reversed: false,
    text: "I find conventional thinking constraining.",
  },
  {
    id: 316,
    facet: "Unconventionality",
    domain: "Openness to Experience",
    reversed: false,
    text: "I value perspectives others dismiss.",
  },
  {
    id: 317,
    facet: "Sociability",
    domain: "Extraversion",
    reversed: false,
    text: "I open conversations easily.",
  },
  {
    id: 318,
    facet: "Forgiveness",
    domain: "Agreeableness",
    reversed: false,
    text: "I let go of resentment readily.",
  },
  {
    id: 319,
    facet: "Inquisitiveness",
    domain: "Openness to Experience",
    reversed: false,
    text: "I want to understand the cause behind every behaviour.",
  },
  {
    id: 320,
    facet: "Creativity",
    domain: "Openness to Experience",
    reversed: false,
    text: "I see possibilities where others see only what already exists.",
  },
];
